name: Run E2E Tests on Pull Request

on:
  pull_request:
    branches:
      - dev
    paths:
      - '**/*.js' # Este é um exemplo, ajuste conforme necessário

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check if PR is from dev to main
        if: github.event.pull_request.base.ref == 'main' && github.event.pull_request.head.ref == 'dev'
        run: echo "PR is from dev to main, continuing..."

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci
      - run: npm run cy:run
