name: run E2E Tests

on:
  push:
    branches: [ "dev" ]

jobs:
  run-e2e-tests:
    name: Run E2E Tests
    runs-on: ubuntu-latest

    steps:
      - name: Check if push is from dev to main
        if: github.ref == 'refs/heads/dev' && github.event_name == 'push' && contains(github.event.ref, 'refs/heads/main')
        run: echo "Push is from dev to main, continuing..."

      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
      
      - run: npm ci
      - run: npm run cy:run
